export const companyServices = [
  {
    id: "development",
    image: "/gallery/compoundPics/engineers-site-office.png",
    titleAr: "التطوير العقاري",
    titleEn: "Real estate development",
    descAr: "تخطيط وتطوير مشاريع سكنية متكاملة بمعايير عالمية.",
    descEn: "Planning and delivering integrated residential projects to global standards.",
  },
  {
    id: "construction",
    image: "/gallery/compoundPics/construction-crew-building-walls.png",
    titleAr: "البناء والتشطيب",
    titleEn: "Construction & finishing",
    descAr: "تنفيذ وإنهاء الوحدات بمواد فاخرة وعزل حراري عالي.",
    descEn: "Building and finishing units with premium materials and strong thermal insulation.",
  },
  {
    id: "management",
    image: "/gallery/compoundPics/housekeeping-team.png",
    titleAr: "إدارة الممتلكات",
    titleEn: "Property management",
    descAr: "متابعة الصيانة والخدمات المشتركة داخل المجتمع.",
    descEn: "Ongoing maintenance and shared-community service oversight.",
  },
  {
    id: "investment",
    image: "/gallery/resortsPics/giant-chess-poolside-royal.png",
    titleAr: "الاستشارات الاستثمارية",
    titleEn: "Investment consulting",
    descAr: "إرشاد المشترين حول العائد والقيمة طويلة الأمد.",
    descEn: "Guiding buyers on return and long-term asset value.",
  },
  {
    id: "financing",
    image: "/gallery/resortsPics/family-lounge-under-pergola.png",
    titleAr: "حلول التمويل",
    titleEn: "Financing solutions",
    descAr: "تقسيط مباشر مع الشركة بدون فوائد وبدون بنك.",
    descEn: "Direct company installments — zero interest, no bank.",
  },
  {
    id: "aftersale",
    image: "/gallery/compoundPics/gardeners-landscaping-park.png",
    titleAr: "ما بعد البيع والضمان",
    titleEn: "After-sale & warranty",
    descAr: "دعم مستمر وفق نظام جودة ISO 9001:2015.",
    descEn: "Ongoing support under ISO 9001:2015 quality systems.",
  },
  {
    id: "legal",
    image: "/gallery/resortsPics/family-entering-resort-front-door.png",
    titleAr: "الدعم القانوني",
    titleEn: "Legal support",
    descAr: "تيسير إجراءات سند الملكية (الطابو) باسم المشتري.",
    descEn: "Facilitating ownership deed (tabou) processing in the buyer’s name.",
  },
] as const;

export const projectAmenities = [
  {
    id: "security",
    titleAr: "الأمن والحراسة",
    titleEn: "Security",
    descAr: "مجتمع مسوّر، حراسة على مدار الساعة، وكاميرات مراقبة.",
    descEn: "Gated community, 24/7 guards, and surveillance cameras.",
  },
  {
    id: "infra",
    titleAr: "البنية التحتية الرقمية",
    titleEn: "Digital infrastructure",
    descAr: "إنترنت ألياف ضوئية، ستلايت، وأنظمة تكييف.",
    descEn: "Fiber internet, satellite, and AC systems.",
  },
  {
    id: "water",
    titleAr: "أنظمة المياه",
    titleEn: "Water systems",
    descAr: "مضخات أوتوماتيكية وتوزيع موثوق للمياه.",
    descEn: "Automatic pumps and reliable water distribution.",
  },
  {
    id: "pools",
    titleAr: "صيانة المسابح",
    titleEn: "Pool systems",
    descAr: "فلترة متقدمة وصيانة دورية للمسابح.",
    descEn: "Advanced filtration and routine pool maintenance.",
  },
  {
    id: "green",
    titleAr: "المساحات الخضراء",
    titleEn: "Green spaces",
    descAr: "حدائق وتنسيق حدائق داخل المجتمع.",
    descEn: "Gardens and landscaping throughout the community.",
  },
  {
    id: "bbq",
    titleAr: "مناطق جلوس وBBQ",
    titleEn: "Seating & BBQ",
    descAr: "برجولات ومناطق شواء مشتركة وخصوصية لكل وحدة.",
    descEn: "Pergolas and BBQ areas — shared and per-unit privacy.",
  },
  {
    id: "parking",
    titleAr: "مواقف السيارات",
    titleEn: "Parking",
    descAr: "كراج لسيارتين لكل وحدة ومواقف للزوار.",
    descEn: "2-car garage per unit plus visitor parking.",
  },
  {
    id: "kids",
    titleAr: "مناطق الأطفال",
    titleEn: "Children’s areas",
    descAr: "مساحات لعب ومسبح أطفال داخل الوحدات والمجتمع.",
    descEn: "Play areas and kids’ pools within units and the community.",
  },
  {
    id: "roads",
    titleAr: "الطرق الداخلية",
    titleEn: "Internal roads",
    descAr: "شبكة طرق داخلية سهلة الوصول.",
    descEn: "Easy-access internal road network.",
  },
  {
    id: "utilities",
    titleAr: "الكهرباء والمرافق",
    titleEn: "Utilities",
    descAr: "توصيلات كهرباء ومرافق مكتملة لكل وحدة.",
    descEn: "Completed electricity and utility connections per unit.",
  },
] as const;
