export const site = {
  nameAr: "روح العطاء",
  nameEn: "Giving City",
  companyAr: "شركة العطاء للتطوير والتمويل العمراني",
  companyEn: "Al-Ataa for City Development & Financing",
  taglineAr: "أول وأكبر مدينة شاليهات مخدومة بالكامل في المنطقة",
  taglineEn: "First and largest fully-serviced chalet city in the region",
  phone: "+962790029928",
  whatsapp: "962790029928",
  whatsappUrl: "https://wa.me/962790029928",
  email: "",
  siteUrl: "https://giving-estate.com",
  mapsUrl: "https://maps.app.goo.gl/PNR3uYsjeDX92fqs7",
  mapsEmbed:
    "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3385.5!2d35.9301!3d31.9497!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zMzHCsDU2JzU5LjAiTiAzNcKwNTUnNDguNCJF!5e0!3m2!1sen!2sjo!4v1",
  locationAr: "٣٩ كم من فندق الرويال باتجاه سحاب الحطمية",
  locationEn: "39 km from Royal Hotel towards Sahab Al-Hatmiyeh",
  coordinates: { lat: 31.949722, lng: 35.930111 },
  hoursAr: {
    weekdays: "الأحد – الخميس: ٩ صباحًا – ٧ مساءً",
    saturday: "السبت: ١٠ صباحًا – ٤ مساءً",
  },
  hoursEn: {
    weekdays: "Sunday – Thursday: 9:00 AM – 7:00 PM",
    saturday: "Saturday: 10:00 AM – 4:00 PM",
  },
  social: {
    instagram: "https://www.instagram.com/giving.city/",
    instagramCorp: "https://www.instagram.com/alataa_development/",
    facebook: "https://www.facebook.com/alataa.giving/",
  },
  contact: "د. طارق قازان",
  contactEn: "Dr. Tarek Qazan",
  iso: "ISO 9001:2015",
  stats: {
    units: 367,
    areaSqm: 500000,
    unitAreaSqm: 500,
    basePriceJd: 168000,
    cashPriceJd: 142800,
    cashDiscountPct: 15,
  },
  videos: {
    tour: "https://www.youtube.com/embed/8D8-mb6opx4",
    iso: "https://www.youtube.com/embed/3Lr4a5EHaRI",
  },
  copyBank: {
    ar: {
      firstLargest: "أول وأكبر مدينة شاليهات مخدومة بالكامل في المنطقة",
      privateResorts: "٣٦٧+ منتجع خاص",
      area: "٥٠٠,٠٠٠ متر مربع",
      deed: "سند ملكية مستقل",
      zeroInterest: "بدون فوائد — مباشرة مع الشركة",
      spanish: "تصميم إسباني فاخر",
      iso: "حاصل على شهادة ISO 9001:2015",
      privacy: "خصوصية تامة — جدران بارتفاع ٣ أمتار",
      investment: "استثمار عقاري مضمون",
    },
    en: {
      firstLargest: "First and largest fully-serviced chalet city in the region",
      privateResorts: "367+ private resorts",
      area: "500,000 square meters",
      deed: "Independent ownership deed",
      zeroInterest: "Zero interest — directly with the company",
      spanish: "Luxury Spanish design",
      iso: "ISO 9001:2015 Certified",
      privacy: "Complete privacy — 3-meter walls",
      investment: "Guaranteed real estate investment",
    },
  },
} as const;
