export type UnitFilterId =
  | "all"
  | "1br"
  | "2br"
  | "3br"
  | "4br"
  | "villa";

export type UnitPlan = {
  id: string;
  filterId: Exclude<UnitFilterId, "all">;
  titleAr: string;
  titleEn: string;
  categoryAr: string;
  categoryEn: string;
  bedrooms: number;
  bathrooms: number;
  /** Phase / zone label shown like JG “floor” */
  floorAr: string;
  floorEn: string;
  maidRoom: "yes" | "no" | "dash";
  parking: number;
  areaSqm: number;
  image: string;
};

export const unitFilters: {
  id: UnitFilterId;
  labelAr: string;
  labelEn: string;
}[] = [
  { id: "all", labelAr: "الكل", labelEn: "All" },
  { id: "1br", labelAr: "غرفة نوم واحدة", labelEn: "1 Bedroom" },
  { id: "2br", labelAr: "غرفتي نوم", labelEn: "2 Bedrooms" },
  { id: "3br", labelAr: "٣ غرف نوم", labelEn: "3 Bedrooms" },
  { id: "4br", labelAr: "٤ غرف نوم", labelEn: "4 Bedrooms" },
  { id: "villa", labelAr: "فيلا", labelEn: "Villa" },
];

export const unitsCopy = {
  ar: {
    title: "الوحدات المتاحة",
    subtitle: "من الوحدات المدمجة إلى الفلل الواسعة، كل وحدة بمساحة تقارب ٥٠٠ م².",
    filterLabel: "تصفية المخططات",
    filterMeta: "٥ أنواع",
    quickView: "عرض سريع",
    bedrooms: "غرف النوم",
    bathrooms: "الحمامات",
    floor: "المرحلة",
    maid: "غرفة خادمة",
    parking: "موقف السيارات",
    maidYes: "نعم",
    maidNo: "لا",
    parkingOne: "١ موقف",
    parkingMany: (n: number) => `${n} مواقف`,
    viewDetails: "عرض تفاصيل المخطط",
    download: "تحميل مخطط الطابق",
  },
  en: {
    title: "Available units",
    subtitle: "From compact units to expansive villas, each on about 500 m².",
    filterLabel: "Filter Plans",
    filterMeta: "5 Types",
    quickView: "Quick View",
    bedrooms: "Bedrooms",
    bathrooms: "Bathrooms",
    floor: "Phase",
    maid: "Maid's Room",
    parking: "Car Parking",
    maidYes: "Yes",
    maidNo: "No",
    parkingOne: "1 Space",
    parkingMany: (n: number) => `${n} Spaces`,
    viewDetails: "View Plan Details",
    download: "Download Floor Plan",
  },
} as const;

/** Placeholder plan images from local gallery until client floor plans arrive. */
export const unitPlans: UnitPlan[] = [
  {
    id: "villa-02",
    filterId: "villa",
    titleAr: "فيلا 02",
    titleEn: "Villa 02",
    categoryAr: "فيلا",
    categoryEn: "Villa",
    bedrooms: 5,
    bathrooms: 6,
    floorAr: "المرحلة ٣",
    floorEn: "Phase 3",
    maidRoom: "yes",
    parking: 4,
    areaSqm: 520,
    image: "/gallery/resortsPics/pool-and-tent-pavilion.png",
  },
  {
    id: "2br-type-06",
    filterId: "2br",
    titleAr: "٢ غرفة نوم، النوع 06",
    titleEn: "2 Bedroom, Type 06",
    categoryAr: "غرفتين نوم",
    categoryEn: "2 Bedrooms",
    bedrooms: 2,
    bathrooms: 3,
    floorAr: "المرحلة ١–٢",
    floorEn: "Phase 1–2",
    maidRoom: "no",
    parking: 2,
    areaSqm: 500,
    image: "/gallery/resortsPics/giant-chess-poolside-royal.png",
  },
  {
    id: "3br-type-03",
    filterId: "3br",
    titleAr: "٣ غرف نوم، النوع 03",
    titleEn: "3 Bedroom, Type 03",
    categoryAr: "٣ غرف نوم",
    categoryEn: "3 Bedrooms",
    bedrooms: 3,
    bathrooms: 4,
    floorAr: "المرحلة ٢",
    floorEn: "Phase 2",
    maidRoom: "yes",
    parking: 2,
    areaSqm: 500,
    image: "/gallery/resortsPics/family-lounge-under-pergola.png",
  },
  {
    id: "villa-01",
    filterId: "villa",
    titleAr: "فيلا 01",
    titleEn: "Villa 01",
    categoryAr: "فيلا",
    categoryEn: "Villa",
    bedrooms: 4,
    bathrooms: 5,
    floorAr: "المرحلة ٣",
    floorEn: "Phase 3",
    maidRoom: "yes",
    parking: 3,
    areaSqm: 510,
    image: "/gallery/resortsPics/swimmer-pool-waterfall.png",
  },
  {
    id: "4br-type-01",
    filterId: "4br",
    titleAr: "٤ غرف نوم، النوع 01",
    titleEn: "4 Bedroom, Type 01",
    categoryAr: "٤ غرف نوم",
    categoryEn: "4 Bedrooms",
    bedrooms: 4,
    bathrooms: 5,
    floorAr: "المرحلة ٢–٣",
    floorEn: "Phase 2–3",
    maidRoom: "yes",
    parking: 3,
    areaSqm: 505,
    image: "/gallery/resortsPics/family-breakfast-poolside-table.png",
  },
  {
    id: "3br-type-02",
    filterId: "3br",
    titleAr: "٣ غرف نوم، النوع 02",
    titleEn: "3 Bedroom, Type 02",
    categoryAr: "٣ غرف نوم",
    categoryEn: "3 Bedrooms",
    bedrooms: 3,
    bathrooms: 3,
    floorAr: "المرحلة ١",
    floorEn: "Phase 1",
    maidRoom: "yes",
    parking: 2,
    areaSqm: 500,
    image: "/gallery/resortsPics/foosball-kids-pool.png",
  },
  {
    id: "3br-type-01-w",
    filterId: "3br",
    titleAr: "٣ غرف نوم، النوع 01 غرب",
    titleEn: "3 Bedroom, Type 01 West",
    categoryAr: "٣ غرف نوم",
    categoryEn: "3 Bedrooms",
    bedrooms: 3,
    bathrooms: 4,
    floorAr: "المرحلة ١",
    floorEn: "Phase 1",
    maidRoom: "yes",
    parking: 2,
    areaSqm: 500,
    image: "/gallery/resortsPics/garden-lounge-kids-swing.png",
  },
  {
    id: "3br-type-01-e",
    filterId: "3br",
    titleAr: "٣ غرف نوم، النوع 01 شرق",
    titleEn: "3 Bedroom, Type 01 East",
    categoryAr: "٣ غرف نوم",
    categoryEn: "3 Bedrooms",
    bedrooms: 3,
    bathrooms: 4,
    floorAr: "المرحلة ١–٢",
    floorEn: "Phase 1–2",
    maidRoom: "yes",
    parking: 2,
    areaSqm: 500,
    image: "/gallery/resortsPics/family-arriving-resort-a9-garage.png",
  },
  {
    id: "2br-type-05",
    filterId: "2br",
    titleAr: "٢ غرفة نوم، النوع 05",
    titleEn: "2 Bedroom, Type 05",
    categoryAr: "غرفتين نوم",
    categoryEn: "2 Bedrooms",
    bedrooms: 2,
    bathrooms: 3,
    floorAr: "المرحلة ٢",
    floorEn: "Phase 2",
    maidRoom: "yes",
    parking: 2,
    areaSqm: 500,
    image: "/gallery/resortsPics/family-entering-resort-front-door.png",
  },
  {
    id: "2br-type-04",
    filterId: "2br",
    titleAr: "٢ غرفة نوم، النوع 04",
    titleEn: "2 Bedroom, Type 04",
    categoryAr: "غرفتين نوم",
    categoryEn: "2 Bedrooms",
    bedrooms: 2,
    bathrooms: 2,
    floorAr: "المرحلة ٢",
    floorEn: "Phase 2",
    maidRoom: "dash",
    parking: 2,
    areaSqm: 500,
    image: "/gallery/resortsPics/quad-bike-royal-clubhouse.png",
  },
  {
    id: "2br-type-03",
    filterId: "2br",
    titleAr: "٢ غرفة نوم، النوع 03",
    titleEn: "2 Bedroom, Type 03",
    categoryAr: "غرفتين نوم",
    categoryEn: "2 Bedrooms",
    bedrooms: 2,
    bathrooms: 3,
    floorAr: "المرحلة ٢",
    floorEn: "Phase 2",
    maidRoom: "yes",
    parking: 2,
    areaSqm: 500,
    image: "/gallery/resortsPics/father-son-bbq-grill.png",
  },
  {
    id: "2br-type-02",
    filterId: "2br",
    titleAr: "٢ غرفة نوم، النوع 02",
    titleEn: "2 Bedroom, Type 02",
    categoryAr: "غرفتين نوم",
    categoryEn: "2 Bedrooms",
    bedrooms: 2,
    bathrooms: 3,
    floorAr: "المرحلة ١",
    floorEn: "Phase 1",
    maidRoom: "yes",
    parking: 2,
    areaSqm: 500,
    image: "/gallery/resortsPics/family-living-room.png",
  },
  {
    id: "2br-type-01",
    filterId: "2br",
    titleAr: "٢ غرفة نوم، النوع 01",
    titleEn: "2 Bedroom, Type 01",
    categoryAr: "غرفتين نوم",
    categoryEn: "2 Bedrooms",
    bedrooms: 2,
    bathrooms: 3,
    floorAr: "المرحلة ١",
    floorEn: "Phase 1",
    maidRoom: "yes",
    parking: 2,
    areaSqm: 500,
    image: "/gallery/resortsPics/master-bedroom-pool-view.png",
  },
  {
    id: "1br-type-02",
    filterId: "1br",
    titleAr: "غرفة نوم واحدة، النوع 02",
    titleEn: "1 Bedroom, Type 02",
    categoryAr: "غرفة نوم واحدة",
    categoryEn: "1 Bedroom",
    bedrooms: 1,
    bathrooms: 2,
    floorAr: "المرحلة ٢",
    floorEn: "Phase 2",
    maidRoom: "no",
    parking: 1,
    areaSqm: 500,
    image: "/gallery/resortsPics/twin-bedroom-pool-view.png",
  },
  {
    id: "1br-type-01",
    filterId: "1br",
    titleAr: "غرفة نوم واحدة، النوع 01",
    titleEn: "1 Bedroom, Type 01",
    categoryAr: "غرفة نوم واحدة",
    categoryEn: "1 Bedroom",
    bedrooms: 1,
    bathrooms: 2,
    floorAr: "المرحلة ١",
    floorEn: "Phase 1",
    maidRoom: "no",
    parking: 1,
    areaSqm: 500,
    image: "/gallery/resortsPics/fireplace-horse-sculpture.png",
  },
];
