export type UnitFilterId =
  | "all"
  | "1br"
  | "2br"
  | "3br"
  | "4br"
  | "villa";

export type UnitPlan = {
  id: string;
  filterId: Exclude<UnitFilterId, "all">;
  titleAr: string;
  titleEn: string;
  categoryAr: string;
  categoryEn: string;
  bedrooms: number;
  bathrooms: number;
  /** Phase / zone label shown like JG “floor” */
  floorAr: string;
  floorEn: string;
  maidRoom: "yes" | "no" | "dash";
  parking: number;
  areaSqm: number;
  image: string;
};

export const unitFilters: {
  id: UnitFilterId;
  labelAr: string;
  labelEn: string;
}[] = [
  { id: "all", labelAr: "الكل", labelEn: "All" },
  { id: "1br", labelAr: "غرفة نوم واحدة", labelEn: "1 Bedroom" },
  { id: "2br", labelAr: "غرفتي نوم", labelEn: "2 Bedrooms" },
  { id: "3br", labelAr: "٣ غرف نوم", labelEn: "3 Bedrooms" },
  { id: "4br", labelAr: "٤ غرف نوم", labelEn: "4 Bedrooms" },
  { id: "villa", labelAr: "فيلا", labelEn: "Villa" },
];

export const unitsCopy = {
  ar: {
    eyebrow: "مخططات الشاليهات",
    title: "روح العطاء",
    introEyebrow: "روح العطاء",
    introHeading: "شاليهات فاخرة مصممة لحياة منتجعية راقية.",
    introCaption:
      "أول وأكبر مدينة شاليهات مخدومة بالكامل في المنطقة — مصممة حول الطريقة التي يرغب الناس فعلاً في العيش بها.",
    introImageAlt: "شاليه روح العطاء بإطلالة على المشروع",
    p1: "٣٦٧+ منتجع خاص على مساحة ٥٠٠,٠٠٠ متر مربع، بمخططات مدروسة بعناية — من الوحدات المدمجة إلى الفلل الواسعة، كل وحدة بمساحة تقارب ٥٠٠ م² وسند ملكية مستقل.",
    p2: "روعيت كل التفاصيل: تصميم إسباني فاخر، وإضاءة طبيعية، وتشطيبات راقية، وخصوصية تامة بجدران بارتفاع ٣ أمتار. صُممت الوحدات حول المسبح والمساحات الخارجية للمعيشة اليومية والاستقبال.",
    p3: "ما يميّز روح العطاء هو ما يحيط بالشاليهات — مرافق مجتمعية كاملة، وإدارة محترفة، وتمويل مباشر بدون فوائد، كلها ضمن عنوان واحد.",
    filterLabel: "تصفية المخططات",
    filterMeta: "٥ أنواع",
    quickView: "عرض سريع",
    bedrooms: "غرف النوم",
    bathrooms: "الحمامات",
    floor: "المرحلة",
    maid: "غرفة خادمة",
    parking: "موقف السيارات",
    maidYes: "نعم",
    maidNo: "لا",
    parkingOne: "١ موقف",
    parkingMany: (n: number) => `${n} مواقف`,
    viewDetails: "عرض تفاصيل المخطط",
    download: "تحميل مخطط الطابق",
  },
  en: {
    eyebrow: "Chalet Plans",
    title: "Giving City",
    introEyebrow: "Giving City",
    introHeading: "Luxury chalets designed for elevated resort living.",
    introCaption:
      "The first and largest fully-serviced chalet city in the region — designed around how people actually want to live.",
    introImageAlt: "Giving City chalet overlooking the project",
    p1: "367+ private resorts across 500,000 m², with carefully considered layouts — from compact units to expansive villas, each ~500 m² with an independent ownership deed.",
    p2: "Every detail is considered: Spanish luxury design, natural light, refined finishes, and complete privacy with 3-meter walls. Units are planned around the pool and outdoor living for everyday life and hosting.",
    p3: "What sets Giving City apart is what surrounds the chalets — full community amenities, professional management, and zero-interest financing directly with the company — all at one address.",
    filterLabel: "Filter Plans",
    filterMeta: "5 Types",
    quickView: "Quick View",
    bedrooms: "Bedrooms",
    bathrooms: "Bathrooms",
    floor: "Phase",
    maid: "Maid's Room",
    parking: "Car Parking",
    maidYes: "Yes",
    maidNo: "No",
    parkingOne: "1 Space",
    parkingMany: (n: number) => `${n} Spaces`,
    viewDetails: "View Plan Details",
    download: "Download Floor Plan",
  },
} as const;

/** Placeholder plan images from local gallery until client floor plans arrive. */
export const unitPlans: UnitPlan[] = [
  {
    id: "villa-02",
    filterId: "villa",
    titleAr: "فيلا – 02",
    titleEn: "Villa — 02",
    categoryAr: "فيلا",
    categoryEn: "Villa",
    bedrooms: 5,
    bathrooms: 6,
    floorAr: "المرحلة ٣",
    floorEn: "Phase 3",
    maidRoom: "yes",
    parking: 4,
    areaSqm: 520,
    image: "/gallery/img_3.jpg",
  },
  {
    id: "2br-type-06",
    filterId: "2br",
    titleAr: "٢ غرفة نوم – النوع 06",
    titleEn: "2 Bedroom — Type 06",
    categoryAr: "غرفتين نوم",
    categoryEn: "2 Bedrooms",
    bedrooms: 2,
    bathrooms: 3,
    floorAr: "المرحلة ١–٢",
    floorEn: "Phase 1–2",
    maidRoom: "no",
    parking: 2,
    areaSqm: 500,
    image: "/gallery/img_5.jpg",
  },
  {
    id: "3br-type-03",
    filterId: "3br",
    titleAr: "٣ غرف نوم – النوع 03",
    titleEn: "3 Bedroom — Type 03",
    categoryAr: "٣ غرف نوم",
    categoryEn: "3 Bedrooms",
    bedrooms: 3,
    bathrooms: 4,
    floorAr: "المرحلة ٢",
    floorEn: "Phase 2",
    maidRoom: "yes",
    parking: 2,
    areaSqm: 500,
    image: "/gallery/img_7.jpg",
  },
  {
    id: "villa-01",
    filterId: "villa",
    titleAr: "فيلا — 01",
    titleEn: "Villa — 01",
    categoryAr: "فيلا",
    categoryEn: "Villa",
    bedrooms: 4,
    bathrooms: 5,
    floorAr: "المرحلة ٣",
    floorEn: "Phase 3",
    maidRoom: "yes",
    parking: 3,
    areaSqm: 510,
    image: "/gallery/img_1.jpg",
  },
  {
    id: "4br-type-01",
    filterId: "4br",
    titleAr: "٤ غرف نوم — النوع 01",
    titleEn: "4 Bedroom — Type 01",
    categoryAr: "٤ غرف نوم",
    categoryEn: "4 Bedrooms",
    bedrooms: 4,
    bathrooms: 5,
    floorAr: "المرحلة ٢–٣",
    floorEn: "Phase 2–3",
    maidRoom: "yes",
    parking: 3,
    areaSqm: 505,
    image: "/gallery/img_9.jpg",
  },
  {
    id: "3br-type-02",
    filterId: "3br",
    titleAr: "٣ غرف نوم — النوع 02",
    titleEn: "3 Bedroom — Type 02",
    categoryAr: "٣ غرف نوم",
    categoryEn: "3 Bedrooms",
    bedrooms: 3,
    bathrooms: 3,
    floorAr: "المرحلة ١",
    floorEn: "Phase 1",
    maidRoom: "yes",
    parking: 2,
    areaSqm: 500,
    image: "/gallery/img_11.jpg",
  },
  {
    id: "3br-type-01-w",
    filterId: "3br",
    titleAr: "٣ غرف نوم — النوع 01 غرب",
    titleEn: "3 Bedroom — Type 01 West",
    categoryAr: "٣ غرف نوم",
    categoryEn: "3 Bedrooms",
    bedrooms: 3,
    bathrooms: 4,
    floorAr: "المرحلة ١",
    floorEn: "Phase 1",
    maidRoom: "yes",
    parking: 2,
    areaSqm: 500,
    image: "/gallery/img_13.jpg",
  },
  {
    id: "3br-type-01-e",
    filterId: "3br",
    titleAr: "٣ غرف نوم — النوع 01 شرق",
    titleEn: "3 Bedroom — Type 01 East",
    categoryAr: "٣ غرف نوم",
    categoryEn: "3 Bedrooms",
    bedrooms: 3,
    bathrooms: 4,
    floorAr: "المرحلة ١–٢",
    floorEn: "Phase 1–2",
    maidRoom: "yes",
    parking: 2,
    areaSqm: 500,
    image: "/gallery/img_15.jpg",
  },
  {
    id: "2br-type-05",
    filterId: "2br",
    titleAr: "٢ غرفة نوم — النوع 05",
    titleEn: "2 Bedroom — Type 05",
    categoryAr: "غرفتين نوم",
    categoryEn: "2 Bedrooms",
    bedrooms: 2,
    bathrooms: 3,
    floorAr: "المرحلة ٢",
    floorEn: "Phase 2",
    maidRoom: "yes",
    parking: 2,
    areaSqm: 500,
    image: "/gallery/img_17.jpg",
  },
  {
    id: "2br-type-04",
    filterId: "2br",
    titleAr: "٢ غرفة نوم — النوع 04",
    titleEn: "2 Bedroom — Type 04",
    categoryAr: "غرفتين نوم",
    categoryEn: "2 Bedrooms",
    bedrooms: 2,
    bathrooms: 2,
    floorAr: "المرحلة ٢",
    floorEn: "Phase 2",
    maidRoom: "dash",
    parking: 2,
    areaSqm: 500,
    image: "/gallery/img_19.jpg",
  },
  {
    id: "2br-type-03",
    filterId: "2br",
    titleAr: "٢ غرفة نوم — النوع 03",
    titleEn: "2 Bedroom — Type 03",
    categoryAr: "غرفتين نوم",
    categoryEn: "2 Bedrooms",
    bedrooms: 2,
    bathrooms: 3,
    floorAr: "المرحلة ٢",
    floorEn: "Phase 2",
    maidRoom: "yes",
    parking: 2,
    areaSqm: 500,
    image: "/gallery/img_21.jpg",
  },
  {
    id: "2br-type-02",
    filterId: "2br",
    titleAr: "٢ غرفة نوم — النوع 02",
    titleEn: "2 Bedroom — Type 02",
    categoryAr: "غرفتين نوم",
    categoryEn: "2 Bedrooms",
    bedrooms: 2,
    bathrooms: 3,
    floorAr: "المرحلة ١",
    floorEn: "Phase 1",
    maidRoom: "yes",
    parking: 2,
    areaSqm: 500,
    image: "/gallery/img_23.jpg",
  },
  {
    id: "2br-type-01",
    filterId: "2br",
    titleAr: "٢ غرفة نوم — النوع 01",
    titleEn: "2 Bedroom — Type 01",
    categoryAr: "غرفتين نوم",
    categoryEn: "2 Bedrooms",
    bedrooms: 2,
    bathrooms: 3,
    floorAr: "المرحلة ١",
    floorEn: "Phase 1",
    maidRoom: "yes",
    parking: 2,
    areaSqm: 500,
    image: "/gallery/img_25.jpg",
  },
  {
    id: "1br-type-02",
    filterId: "1br",
    titleAr: "غرفة نوم واحدة — النوع 02",
    titleEn: "1 Bedroom — Type 02",
    categoryAr: "غرفة نوم واحدة",
    categoryEn: "1 Bedroom",
    bedrooms: 1,
    bathrooms: 2,
    floorAr: "المرحلة ٢",
    floorEn: "Phase 2",
    maidRoom: "no",
    parking: 1,
    areaSqm: 500,
    image: "/gallery/img_29.jpg",
  },
  {
    id: "1br-type-01",
    filterId: "1br",
    titleAr: "غرفة نوم واحدة — النوع 01",
    titleEn: "1 Bedroom — Type 01",
    categoryAr: "غرفة نوم واحدة",
    categoryEn: "1 Bedroom",
    bedrooms: 1,
    bathrooms: 2,
    floorAr: "المرحلة ١",
    floorEn: "Phase 1",
    maidRoom: "no",
    parking: 1,
    areaSqm: 500,
    image: "/gallery/img_31.jpg",
  },
];
